### ISSUE TITLE
[BUG] Font class causes segmentation fault if its never initialized

### ISSUE THREAD

**Issue by Toasterbirb** [Toasterbirb/Birb2D#34]
**Describe the bug**
Creating a font object and never actually initializing it causes a segmentation fault when the scope that the font is in ends.

Stacktrace:
```
#0  0x00007ffff7f7a302 in Flush_Cache (font=0x40400000) at /home/toasterbirb/birb2d/vendor/SDL_ttf/SDL_ttf.c:2084
#1  0x00007ffff7f7bcaf in TTF_CloseFont (font=0x40400000) at /home/toasterbirb/birb2d/vendor/SDL_ttf/SDL_ttf.c:2739
#2  0x00005555556127e8 in Birb::Font::~Font (this=0x7fffffffcd38, __in_chrg=<optimized out>) at /home/toasterbirb/birb2d/src/font.cpp:22
#3  0x00005555555ece22 in Birb::Splash::~Splash (this=0x7fffffffccc0, __in_chrg=<optimized out>) at /home/toasterbirb/birb2d/include/Splash.hpp:9
#4  0x00005555555ebed8 in Birb::_DOCTEST_ANON_FUNC_2 () at /home/toasterbirb/birb2d/tests/splash_test.cpp:11
#5  0x000055555557afef in doctest::Context::run (this=0x7fffffffd8c0) at /home/toasterbirb/birb2d/include/doctest.h:6486
#6  0x000055555557ba8a in main (argc=1, argv=0x7fffffffd9f8) at /home/toasterbirb/birb2d/tests/doctest_entry.cpp:22
```

**To Reproduce**
Create a font and never use any of its constructors. Wait until the font gets destroyed and enjoy the segfault

**Expected behavior**
The font class doesn't try to free its non-existant TTF_Font

**Actual behavior**
The font class attempts to free a non-existant font (or that is at least my guess)

**Comment by Toasterbirb** [comment]
This can also cause another segfault with an entity that points to a Font object that is not initialized if the Entity is destroyed
